### ISSUE TITLE
Update configuration step in instructions

### ISSUE THREAD

**Issue by jaxatto** [shyaniv7/react-native-fontawesome-pro#13]
### Description
Instructions give out of date guidance on how to setup .npmrc, sources:

- https://blog.fontawesome.com/locking-the-vault-on-font-awesome-npm-tokens-9a023bd0dd65?gi=2ea5d90f2f99 
- https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers 

From this:
`@fortawesome:registry=https://npm.fontawesome.com/<TOKEN>`

to this:
`@fortawesome:registry=https://npm.fontawesome.com/`
`//npm.fontawesome.com/:_authToken=<TOKEN>`

I was wondering if this needs repo's instructions need to be updated to reflect this change from FontAwesome?

**Comment by shyaniv7** [comment]
You are correct the readme should be updated
