### ISSUE TITLE
Add `activeOpacity` prop

### ISSUE THREAD

**Issue by mvanroon** [shyaniv7/react-native-fontawesome-pro#14]
### Description
The `<TouchableOpacity>`'s `activeOpacity` determines what the opacity of the wrapped view should be when touch is active. It defaults to 0.2 and in some cases, this is far too opaque.

I was thinking of creating a merge request that allows for this prop to be passed on to the `<Icon>`'s wrapping `<TouchableOpacity>` but this could mean that people want other props (such as `hitSlop` or `onLongPress` for example) to be added too.

One could always just skip the `onPress` prop and wrap the `<Icon>` in a `<TouchableOpacity>` themselves in order to have full control.

Thoughts?

**Comment by beausmith** [comment]
@mvanroon - check out this commit: https://github.com/shyaniv7/react-native-fontawesome-pro/pull/16/commits/4be5f6f92843703919e1fbeb1e87c83b92cf0026

**Comment by beausmith** [comment]
Yay!

**Comment by mvanroon** [comment]
I guess we’re skipping the discussion then!

**Comment by shyaniv7** [comment]
I figured it won’t hurt to add this as a prop.
The users still have the flexibility of not adding the onPress which wraps the icon with the touchable and wrapping it themselves. Active opacity seemed like a basic prop with a default value that doesn’t hurt.

The next time we add a special prop just for the touchable that’s when I think we need to come up eth a better strategy.
