### ISSUE TITLE
Unexpected view type nested

### ISSUE THREAD

**Issue by Julian367** [shyaniv7/react-native-fontawesome-pro#19]
Hello, 

### Description

![screenshot_2018-08-06-15-08-11 1](https://user-images.githubusercontent.com/7355974/43715925-da9be2f2-998a-11e8-97b4-fe8e9e117ad5.png)

### Environment

* What `react-native-fontawesome-pro` version 
**are you using?  2.0.1**
* What `react-native` version are you using? 
 **sdk-28.0.0**
* Does the issue occur on IOS, Android or Both? 
**only Android**

Maybe this may help also:

import Icon from "react-native-fontawesome-pro";

Could not find a declaration file for module 'react-native-fontawesome-pro'. 'c:/My-app/node_modules/react-native-fontawesome-pro/index.js' implicitly has an 'any' type.
  Try `npm install @types/react-native-fontawesome-pro` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-native-fontawesome-pro';

**Comment by shyaniv7** [comment]
This issue has been resolved in `react-native-fontawesome-pro@2.1.0`
