### ISSUE TITLE
Unable to enter token when using yarn install

### ISSUE THREAD

**Issue by eaco-andrew** [shyaniv7/react-native-fontawesome-pro#2]
Unable to enter token when using yarn install

**Comment by shyaniv7** [comment]
Hey @eaco-andrew Thank you for letting me know.

In version 1.0.10 that will come out tonight or tomorrow the consumer of the package will be responsible of creating a `.npmrc` file and installing `react-native-svg` that will remove the manual linking steps and also allow this component to work both on ios and android.

**Comment by eaco-andrew** [comment]
That sounds great.

Love your work!

**Comment by shyaniv7** [comment]
@eaco-andrew `1.0.11` was just published please follow the instructions in the readme in the right order

```js
1) // create a .npmrc with the fontawesome registry and your token reference the README.md
2) npm install react-native-svg --save
3) react-native link react-native-svg
4) npm install react-native-fontawesome-pro
```
Enjoy!
