### ISSUE TITLE
Icon size difference

### ISSUE THREAD

**Issue by odesey** [shyaniv7/react-native-fontawesome-pro#22]
### Description
Firstly, thanks for this great package!
I have noticed that there is a substantial size difference with the icons from this package and the ones used in `react-native-vector-icons`. 

Both are set to `size={24}`

![size](https://user-images.githubusercontent.com/3899366/45046571-862a8b80-b044-11e8-8f55-b48bf4e3aa6e.png)

Is this a bug?

### Environment

* What `react-native-fontawesome-pro` version are you using? **2.0.1**
* What `react-native` version are you using? **0.51.0**
* Does the issue occur on IOS, Android or Both? **Both**

**Comment by shyaniv7** [comment]
I am not sure what icon set is used be `react-native-vector-icons`, I directly use the fontawesome-pro packages and their svg content is rendered using the `react-native-svg` package.

It might have something to do with your wrapping component
