### ISSUE TITLE
TypeError: Cannot read property 'icon' of undefined

### ISSUE THREAD

**Issue by dhawala190** [shyaniv7/react-native-fontawesome-pro#27]
### Description
When trying to render Icon it gives "TypeError: Cannot read property 'icon' of undefined
" error. When looked up in detail, the method findIconDefinition() from "@fortawesome/fontawesome-svg-core" doesn't return an icon instead returns undefined.
This wasn't the case one week back. 

### Environment

react-native-fontawesome-pro version : 2.0.1
react-native: 0.57.7
* Does the issue occur on IOS, Android or Both?
Android: yes
iOS: didn't test

**Comment by dhawala190** [comment]
It was a typo in configuring FontAwesome Pro.
Closing the issue.

**Comment by export-mike** [comment]
@dhawala190 what was the typo? I'm getting the same issue :D

**Comment by solonifer** [comment]
Getting the same error
