### ISSUE TITLE
Get image source path to use in TabBar/NavigatorIOS

### ISSUE THREAD

**Issue by solonifer** [shyaniv7/react-native-fontawesome-pro#8]
### Description

Can I get source path of the icon like getImageSource in https://github.com/oblador/react-native-vector-icons to use in TabBar/NavigatorIOS?

**Comment by shyaniv7** [comment]
The way this lib works is that I extract the svg of the fontawesome icon and render it on the screen using `react-native-svg`

There is no way to get an actual source other than the svg it self.
You are welcome to look at the source code.

If you think that the svg content is sufficient for what youre trying to achieve I can expose a method for you to use that will retrieve the svg for you

something along the lines of
```
import { getIconSvgSource } from "react-native-fontawesome-pro"

const svgSource = getIconSvgSource( "icon name" );
```

does that work for you?

**Comment by solonifer** [comment]
Hi @shyaniv7,

Thank you for reply!
I'm not sure yet 🤔 - but I think it maybe helpful.

I need to use it with react-native-navigation as tabs icon. So I need to dive into it and see how can I do magic with both of this 🙃

So if this is not a big deal, I think it can be helpful to other people anyway 🍻 (if not to me)
